### ISSUE TITLE
Ranges

### ISSUE THREAD

**Issue by CurtesMalteser** [swisspost/apikana#212]
Is it possible to add ranges validation?
Writing as issue because couldn't find support.
I see that Swagger spec allows min. and max. values and I would like to have that feature.

**Comment by lbovet** [comment]
Yes, you can use annotations that are supported by [typescript-json-schema](https://github.com/YousefED/typescript-json-schema)
You have min/max examples here
https://github.com/YousefED/typescript-json-schema/blob/master/example/invoice/line.ts#L26-L38

**Comment by CurtesMalteser** [comment]
Perfect. Thank you.
